In [55]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [56]:
df = pd.read_csv('dirtydata.csv')
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [57]:
df.shape

(32, 5)

In [58]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  266.013333
std     70.039591    7.832933   12.998759  164.876415
min     30.000000   90.000000  101.000000 -300.000000
25%     60.000000  100.000000  120.000000  247.000000
50%     60.000000  102.500000  127.500000  282.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [59]:
df.dtypes

Duration      int64
Date            str
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [60]:
df.tail(10)

    Duration          Date  Pulse  Maxpulse  Calories
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132    -280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Replacing Negative with positive values

In [61]:
df1=df
df['Calories'] = df['Calories'].abs()
df.tail(10)

    Duration          Date  Pulse  Maxpulse  Calories
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [62]:
df1.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

## Findind Missing Values

In [63]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

## Filling Missing Values

In [64]:
x = df['Calories'].mean()
x

np.float64(304.68)

In [65]:
df['Calories']=df['Calories'].fillna(x)

In [66]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [67]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

## Droping null data using subset

In [68]:
df.dropna(subset=['Date'], inplace=True)
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

## Changing Datatype

In [69]:
df['Calories'] = df['Calories'].astype(int)
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130       409
1        60  '2020/12/02'    117       145       479
2        60  '2020/12/03'    103       135       340
3        45  '2020/12/04'    109       175       282
4        45  '2020/12/05'    117       148       406

In [70]:
df.dtypes

Duration    int64
Date          str
Pulse       int64
Maxpulse    int64
Calories    int64
dtype: object

# Replacing on particular location

In [71]:
df.loc[7, 'Duration'] = 45
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130       409
1        60  '2020/12/02'    117       145       479
2        60  '2020/12/03'    103       135       340
3        45  '2020/12/04'    109       175       282
4        45  '2020/12/05'    117       148       406

## Finding and Droping Duplicates

In [72]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool

In [73]:
df.drop_duplicates(inplace=True)
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130       409
1        60  '2020/12/02'    117       145       479
2        60  '2020/12/03'    103       135       340
3        45  '2020/12/04'    109       175       282
4        45  '2020/12/05'    117       148       406

# NBA Data

In [74]:
data = pd.read_csv('nba.csv')
data.tail(5)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
data.dtypes

Name            str
Team            str
Number      float64
Position        str
Age         float64
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

# Replacing Categorical data with quantitative data

In [76]:
data['Position'].value_counts()

Position
SG    102
PF    100
PG     92
SF     85
C      78
Name: count, dtype: int64

## Using replace function

In [77]:
data['Position'].replace(['SG','PF','PG','SF','C'],[0,1,2,3,4], inplace= True)
data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Using Label Encoding

In [78]:
import pandas as pd

In [79]:
data_nba = pd.read_csv('nba.csv')

In [80]:
from sklearn import preprocessing

In [81]:
data_nba['Position'].unique()

<ArrowStringArray>
['PG', 'SF', 'SG', 'PF', 'C', nan]
Length: 6, dtype: str

In [82]:
label_encoder = preprocessing.LabelEncoder()
data_nba['Position'] = label_encoder.fit_transform(data_nba['Position'])

In [83]:
data_nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,2,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,3,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,4,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,4,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,1,29.0,6-10,231.0,NaN,5000000.0

In [84]:
data_nba.dtypes

Name            str
Team            str
Number      float64
Position      int64
Age         float64
Height          str
Weight      float64
College         str
Salary      float64
dtype: object

In [85]:
data_nba['Position'].unique()

array([2, 3, 4, 1, 0, 5])

To fill nan in salary according to position

In [86]:
data_nba['Salary']=data_nba['Salary'].fillna(data_nba.groupby('Position')['Salary'].transform('mean'))

# Quantitative to Categorical using pandas cut

In [87]:
category = pd.cut(data_nba.Age, bins=[19,25,30,35,45], labels=['A', 'B', 'C', 'D'])

In [88]:
data_nba.insert(5, 'Age_Group', category)

In [89]:
data_nba.head()

,Name,Team,Number,Position,Age,Age_Group,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,2,25.0,A,6-2,180.0,Texas,7.730337e+06
1,Jae Crowder,Boston Celtics,99.0,3,25.0,A,6-6,235.0,Marquette,6.796117e+06
2,John Holland,Boston Celtics,30.0,4,27.0,B,6-5,205.0,Boston University,4.009861e+06
3,R.J. Hunter,Boston Celtics,28.0,4,22.0,A,6-5,185.0,Georgia State,1.148640e+06
4,Jonas Jerebko,Boston Celtics,8.0,1,29.0,B,6-10,231.0,NaN,5.000000e+06

# Saved Dataframe to csv

In [90]:
data_nba.to_csv('NBA-Data.csv')

In [91]:

df.columns = df.columns.str.strip() # Leading and trailing
df.columns = df.columns.str.lstrip() # Leading only
df.columns = df.columns.str.rstrip() # Trailing only

df = df.rename(columns=lambda x: x.strip()) # Slower alternative